### PR TITLE
Add support for "check program" ( type == 7 )

### PR DESCRIPTION
**Pull request by Marqin**
This patch:
- Remove some unnecessary whitespace
- Add support for "check program" ( type == 7 )
- Change "dont_show_alerts" behaviour code, so now it's
    independent from "Alerts" collumn id, which was needed
    to avoid another if-case for type 7.

This patch also add storing "check program" output to XML,
which is currently unused by frontend ( but support may be added ).

### CODE REVIEW

**Comment by Marqin** [comment]
@danschultzer
I've created PR, as You requested in #2.

**Comment by Marqin** [comment]
If you think it's better not to write $program_output to XML to spare disk space, then I can comment it out.

**Comment by danschultzer** [comment]
> If you think it's better not to write $program_output to XML to spare disk space, then I can comment it out.

Yeah, I think it's better to remove that part. It's always better to just have the logic that's actually being used, and not any unused logic that'll just confuse. It can always be added in later when it's going to be used.

**Comment by Marqin** [comment]
> Yeah, I think it's better to remove that part.

Done.

**Comment by danschultzer** [comment]
:+1:

**Pull request merged**
